name: downloadaccelerator
version: '2.0'
summary: A free tool to download files. 
description: |
  Download Accelerator is a free and open source software application that
  allows quickly downloading of files on the web.
  
  Download Accelerator contains two parts. This part which downloads files 
  and another part which is a firefox extension. Indeed if you want to benefit
  all fonctionalities of this application you must install the two parts.

  You can launch it from command line by typing "downloadaccelerator",
  from desktop activities by clicking to its icon and from web browser firefox 
  if you are installed its extension.

base: core18
confinement: strict
grade: stable

apps:
  downloadaccelerator:
    extensions:
      - gnome-3-28
    command: desktop-launch $JAVA_BIN -jar $SNAP/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION.jar  client
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAPCRFT_TARGET_ARCH
      JAVA_BIN: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAPCRFT_TARGET_ARCH/bin/java
      PATH: $SNAP/bin:$SNAP/sbin:$SNAP/usr/bin:$SNAP/usr/sbin:$JAVA_HOME/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11

  downloadacceleratorserver:
    command: desktop-launch $JAVA_BIN -jar $SNAP/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION.jar server
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAPCRFT_TARGET_ARCH
      JAVA_BIN: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAPCRFT_TARGET_ARCH/bin/java
      PATH: $SNAP/bin:$SNAP/sbin:$SNAP/usr/bin:$SNAP/usr/sbin:$JAVA_HOME/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH
    autostart: $SNAPCRAFT_PROJECT_NAME-server.desktop
    plugs:
      - home
      - dbus
      - gsettings
      - removable-media
      - browser-support
      - opengl
      - network
      - network-bind
      - desktop 
      - desktop-legacy
      - x11

parts:
  downloadaccelerator:
    plugin: nil
    source: . ###https://github.com/messey-bilal/downloadaccelerator.git
    #source-tag: release-$SNAPCRAFT_PROJECT_VERSION
    override-build: |
      gradle build
      cp -r images $SNAPCRAFT_PART_INSTALL/
      cp build/libs/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION.jar $SNAPCRAFT_PART_INSTALL/
      mkdir $SNAPCRAFT_PART_INSTALL/autostart
      cp $SNAPCRAFT_PROJECT_NAME-server.desktop $SNAPCRAFT_PART_INSTALL/autostart
      cp setupDesktopServer.sh $SNAPCRAFT_PART_INSTALL/autostart
      chmod +x $SNAPCRAFT_PART_INSTALL/autostart/setupDesktopServer.sh
    build-packages:
      - gradle
    stage-packages:
      - openjdk-11-jre
