name: downloadaccelerator
version: '2.0'
summary: A free tool to download files. 
description: |
  Download Accelerator is a free and open source software application that
  allows quickly downloading of files on the web.
  
  Download Accelerator contains two parts. This part which downloads files 
  and another part which is a firefox extension. Indeed if you want to benefit
  all fonctionalities of this application you must install the two parts.

  You can launch it from command line by typing "downloadaccelerator",
  from desktop activities by clicking to its icon and from web browser firefox 
  if you are installed its extension.

base: core20
confinement: strict
grade: stable

apps:
  downloadaccelerator:
    command: $SNAPCRAFT_PRIME/$SNAPCRAFT_PROJECT_NAME.sh
    plugs:
      - home
      - network
      - network-bind
      - cups-control
      - desktop
      - desktop-legacy
      - x11

  downloadacceleratorserver:
    command: $SNAPCRAFT_PRIME/$SNAPCRAFT_PROJECT_NAME.sh server
    passthrough:
      autostart: $SNAPCRAFT_PROJECT_NAME-server.desktop
    plugs:
      - home
      - network
      - network-bind
      - cups-control
      - desktop 
      - desktop-legacy
      - x11
 
parts:
  downloadaccelerator:
    plugin: nil
    source: . ###https://github.com/messey-bilal/downloadaccelerator.git
    #source-tag: release-$SNAPCRAFT_PROJECT_VERSION
    override-build: |
      gradle build
      cp -r images $SNAPCRAFT_PART_INSTALL/
      cp build/libs/$SNAPCRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION.jar $SNAPCRAFT_PART_INSTALL/
      cp $SNAPCRAFT_PROJECT_NAME.sh $SNAPCRAFT_PART_INSTALL/
      cp $SNAPCRAFT_PROJECT_NAME-server.desktop $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - gradle
    stage-packages:
      - openjdk-11-jre
