name: downloadaccelerator
version: '3.2'
summary: A free tool to download files.
description: |
    Download Accelerator is a free and open source software application that allows quickly downloading of files on the web.
    Download Accelerator contains two parts. This part which downloads files and another part which is a firefox extension. Indeed if you want to benefit all fonctionalities of this application you must install the two parts.
    You can launch it from command line by typing "downloadaccelerator", from desktop activities by clicking to its icon and from web browser firefox if you are installed its extension.

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  downloadaccelerator:
    extensions:
      - gnome
    command: usr/bin/setup.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-$CRAFT_TARGET_ARCH
      JAVA_BIN: $SNAP/usr/lib/jvm/java-17-openjdk-$CRAFT_TARGET_ARCH/bin/java
      PATH: $SNAP/usr/bin:$SNAP/usr/sbin:/snap/gnome-42-2204-sdk/current/usr/bin:$JAVA_HOME/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR-linux-gnu:/snap/gnome-42-2204-sdk/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/gnome-42-2204-sdk/current/usr/lib:/snap/gnome-42-2204-sdk/current/usr/lib/vala-current:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - gnome-42-2204
 
  downloadacceleratorserver:
    extensions:
      - gnome
    command: usr/bin/setup.sh server
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-$CRAFT_TARGET_ARCH
      JAVA_BIN: $SNAP/usr/lib/jvm/java-17-openjdk-$CRAFT_TARGET_ARCH/bin/java
      PATH: $SNAP/usr/bin:$SNAP/usr/sbin:/snap/gnome-42-2204-sdk/current/usr/bin:$JAVA_HOME/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR-linux-gnu:/snap/gnome-42-2204-sdk/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/gnome-42-2204-sdk/current/usr/lib:/snap/gnome-42-2204-sdk/current/usr/lib/vala-current:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    autostart: $CRAFT_PROJECT_NAME-server.desktop
    plugs:
      - home
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - gnome-42-2204
  

parts:
  downloadaccelerator:
    plugin: nil
    source: .
    override-build: |
      mv images $CRAFT_PART_INSTALL/
      mkdir $CRAFT_PART_INSTALL/autostart
      install $CRAFT_PROJECT_NAME-server.desktop $CRAFT_PART_INSTALL/autostart
      install setup.sh $CRAFT_PART_INSTALL/usr/bin
      chmod +x $CRAFT_PART_INSTALL/usr/bin/setup.sh
      chmod +x build.sh && ./build.sh && install $CRAFT_PROJECT_NAME-$SNAPCRAFT_PROJECT_VERSION.jar $CRAFT_PART_INSTALL/
    build-packages:
      - openjdk-17-jdk-headless
      - openjdk-17-jre-headless
      - ca-certificates-java
      - ca-certificates
    stage-packages:
      - openjdk-17-jre
      - openjdk-17-jre-headless
      - ffmpeg
      - libavdevice58
      - libavfilter7
      - libpostproc55
      - libavformat58
      - libavcodec58
      - libswresample3
      - libswscale5
      - libavutil56
      - libslang2
      - libglu1-mesa
      - freeglut3
